-- 1. Aggregation: Total number of bookings made by each user

SELECT 
    USER.ID AS USER_ID,
    USER.NAME,
    COUNT(BOOKING.ID) AS TOTAL_BOOKINGS
FROM 
    USER
LEFT JOIN 
    BOOKING ON USER.ID = BOOKING.USER_ID
GROUP BY 
    USER.ID, USER.NAME
ORDER BY 
    TOTAL_BOOKINGS DESC;



-- 2. Window function: Rank properties based on total bookings using ROW_NUMBER()

SELECT 
    PROPERTY.ID AS PROPERTY_ID,
    PROPERTY.NAME,
    COUNT(BOOKING.ID) AS TOTAL_BOOKINGS,
    ROW_NUMBER() OVER (ORDER BY COUNT(BOOKING.ID) DESC) AS ROW_NUM_RANK
FROM 
    PROPERTY
LEFT JOIN 
    BOOKING ON PROPERTY.ID = BOOKING.PROPERTY_ID
GROUP BY 
    PROPERTY.ID, PROPERTY.NAME
ORDER BY 
    ROW_NUM_RANK;



-- 3. Window function: Rank properties based on total bookings using RANK()

SELECT 
    PROPERTY.ID AS PROPERTY_ID,
    PROPERTY.NAME,
    COUNT(BOOKING.ID) AS TOTAL_BOOKINGS,
    RANK() OVER (ORDER BY COUNT(BOOKING.ID) DESC) AS RANK_POSITION
FROM 
    PROPERTY
LEFT JOIN 
    BOOKING ON PROPERTY.ID = BOOKING.PROPERTY_ID
GROUP BY 
    PROPERTY.ID, PROPERTY.NAME
ORDER BY 
    RANK_POSITION;
