SELECT 
    USER.ID AS USER_ID,
    USER.NAME,
    COUNT(BOOKING.ID) AS TOTAL_BOOKINGS
FROM 
    USER
LEFT JOIN 
    BOOKING ON USER.ID = BOOKING.USER_ID
GROUP BY 
    USER.ID, USER.NAME
ORDER BY 
    TOTAL_BOOKINGS DESC;
-- This query retrieves the total number of bookings made by each user,

SELECT 
    PROPERTY.ID AS PROPERTY_ID,
    PROPERTY.HOST_ID,
    COUNT(BOOKING.ID) AS TOTAL_BOOKINGS,
    RANK() OVER (ORDER BY COUNT(BOOKING.ID) DESC) AS PROPERTY_RANK
FROM 
    PROPERTY
LEFT JOIN 
    BOOKING ON PROPERTY.ID = BOOKING.PROPERTY_ID
GROUP BY 
    PROPERTY.ID, PROPERTY.HOST_ID
ORDER BY 
    PROPERTY_RANK;
-- ranking properties based on the number of bookings they have received.