-- 1. Aggregation: Total number of bookings made by each user

SELECT 
    USER.ID AS USER_ID,
    USER.NAME,
    COUNT(BOOKING.ID) AS TOTAL_BOOKINGS
FROM 
    USER
LEFT JOIN 
    BOOKING ON USER.ID = BOOKING.USER_ID
GROUP BY 
    USER.ID, USER.NAME
ORDER BY 
    TOTAL_BOOKINGS DESC;



-- 2. Window function: Rank properties based on total number of bookings using ROW_NUMBER()

SELECT 
    PROPERTY.ID AS PROPERTY_ID,
    PROPERTY.NAME,
    COUNT(BOOKING.ID) AS TOTAL_BOOKINGS,
    ROW_NUMBER() OVER (ORDER BY COUNT(BOOKING.ID) DESC) AS PROPERTY_RANK
FROM 
    PROPERTY
LEFT JOIN 
    BOOKING ON PROPERTY.ID = BOOKING.PROPERTY_ID
GROUP BY 
    PROPERTY.ID, PROPERTY.NAME
ORDER BY 
    PROPERTY_RANK;
